# Generated by Django 4.1.13 on 2024-02-01 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stockdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_stocks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
