# Generated by Django 4.1.13 on 2024-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0003_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="splitsdividends",
            name="dividend_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="splitsdividends",
            name="ex_dividend_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="splitsdividends",
            name="forward_annual_dividend_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="splitsdividends",
            name="forward_annual_dividend_yield",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="splitsdividends",
            name="last_split_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="splitsdividends",
            name="payout_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
