# Generated by Django 4.1.13 on 2024-02-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0004_alter_splitsdividends_dividend_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="filing_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
