# Generated by Django 4.1.13 on 2024-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0005_alter_cashflow_filing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesheet",
            name="filing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="filing_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
