# Generated by Django 4.1.13 on 2024-02-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0007_stockprices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockprices",
            name="Y10",
        ),
        migrations.RemoveField(
            model_name="stockprices",
            name="Y11",
        ),
        migrations.RemoveField(
            model_name="stockprices",
            name="Y7",
        ),
        migrations.RemoveField(
            model_name="stockprices",
            name="Y8",
        ),
        migrations.RemoveField(
            model_name="stockprices",
            name="Y9",
        ),
        migrations.RemoveField(
            model_name="stockprices",
            name="cagr_10_years",
        ),
    ]
