# Generated by Django 4.1.13 on 2024-02-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0008_remove_stockprices_y10_remove_stockprices_y11_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DividendYieldData",
            fields=[
                (
                    "general",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dividend_yield_data",
                        serialize=False,
                        to="stockdata.general",
                    ),
                ),
                (
                    "yield_Y1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "yield_Y2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "yield_Y3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "yield_Y4",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "yield_Y5",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "cagr_5_years",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dividend Yield Data",
            },
        ),
    ]
