# Generated by Django 4.1.13 on 2024-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0010_remove_general_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="uid",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="general",
            name="primary_ticker",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
