# Generated by Django 4.1.13 on 2024-02-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0014_remove_balancesheet_accounts_payable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
