# Generated by Django 4.1.13 on 2024-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0016_alter_general_country_iso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesheet",
            name="type",
            field=models.CharField(
                choices=[("yearly", "Yearly"), ("quarterly", "Quarterly")],
                default="yearly",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="type",
            field=models.CharField(
                choices=[("yearly", "Yearly"), ("quarterly", "Quarterly")],
                default="yearly",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="type",
            field=models.CharField(
                choices=[("yearly", "Yearly"), ("quarterly", "Quarterly")],
                default="yearly",
                max_length=100,
            ),
        ),
    ]
