# Generated by Django 4.1.13 on 2024-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0018_prices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prices",
            old_name="today",
            new_name="close",
        ),
        migrations.RenameField(
            model_name="prices",
            old_name="yesterday",
            new_name="prev_close",
        ),
        migrations.AddField(
            model_name="prices",
            name="change_p",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
