# Generated by Django 4.1.13 on 2024-01-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usermanagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
