# Generated by Django 4.1.13 on 2024-02-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usermanagement", "0003_customuser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
