# Generated by Django 4.1.13 on 2024-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usermanagement", "0004_customuser_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
